#include "app.h"

char PCComm[50];
char PCDebug[50];
char table_names[5][5] = { "xxxx", "xxxx", "xxxx", "xxxx", "xxxx" };
uint16_t angle_raw;
RangeAngle table_data[TABLE_SIZE];
uint8_t pageBuffer[PAGE_BUFFER_SIZE];
uint8_t CommPointer = 0;
uint8_t CommAv = 0;
uint8_t MsgSize = 0xFF;
unsigned long CommStart;
unsigned long sleep_timer = 56000;
char Code_revision[] = "-1-";
char Date[] = "07/11/2024";
char value[7];
char message[] = "135.0";
char SSD13003_PAGE[7];
char SSD13003_COL[7];
unsigned short comm;
uint8_t screen_buffer[64][6];
uint8_t bat_per_prev = 0;
uint8_t table_num = 1;
uint8_t roll_state = 10;
uint8_t activate_sleep = 0;
bool button_one_check = false;
bool button_two_check = false;
bool button_one_long_press = false;
bool button_both_check = false;
bool display_off = false;
int16_t lcd_brightness = 127;
uint8_t test_Var = 0;
uint8_t active_tables = 0;
unsigned long roll_timer;
unsigned long timebase = 0;
unsigned long printtime = 0;
unsigned long sampletime = 0;
unsigned long screen_dim = 0;
unsigned long button_timer_one = 0;
unsigned long button_timer_two = 0;
unsigned long button_timer_both = 0;
uint16_t raw_angle;
uint16_t adc_count;
float cur_ang = 0.0f;
float input_voltage;
float zero_angle = 0.0f;
uint8_t blinkflip = 0;
uint8_t blink_roll = 0;
int16_t roll_angle;
int16_t main_cycle = 0;
bool show_clear_flag = false;
